// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLoX3LA0a85Mv1Hka86UAdSocVsR9O0sg',
    appId: '1:86070082877:web:a6504e1c89bebb16479954',
    messagingSenderId: '86070082877',
    projectId: 'socialapp-43677',
    authDomain: 'socialapp-43677.firebaseapp.com',
    storageBucket: 'socialapp-43677.firebasestorage.app',
    measurementId: 'G-WX542DC01V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA86Whm7Ua4kOc-7xvjBkIEGXfh60sBmCQ',
    appId: '1:86070082877:android:d3e8918a03ee83ff479954',
    messagingSenderId: '86070082877',
    projectId: 'socialapp-43677',
    storageBucket: 'socialapp-43677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfa94CnRFCQxaHBqetjvjrUe4Miib4P9Y',
    appId: '1:86070082877:ios:60a65d6cc30f6778479954',
    messagingSenderId: '86070082877',
    projectId: 'socialapp-43677',
    storageBucket: 'socialapp-43677.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfa94CnRFCQxaHBqetjvjrUe4Miib4P9Y',
    appId: '1:86070082877:ios:60a65d6cc30f6778479954',
    messagingSenderId: '86070082877',
    projectId: 'socialapp-43677',
    storageBucket: 'socialapp-43677.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLoX3LA0a85Mv1Hka86UAdSocVsR9O0sg',
    appId: '1:86070082877:web:b3ccc6590e405f7a479954',
    messagingSenderId: '86070082877',
    projectId: 'socialapp-43677',
    authDomain: 'socialapp-43677.firebaseapp.com',
    storageBucket: 'socialapp-43677.firebasestorage.app',
    measurementId: 'G-34BHYRW1C7',
  );
}
